name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

    
      - name: Build project
        run: dotnet publish krypteringAPI/krypteringAPI.csproj -c Release -o site

    
      - name: Create deployment package
        run: cd site && zip -r ../site.zip *

    
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: EnkrypteringAPI
          environment_name: EnkrypteringAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip

